name: CI - build, test, SAST

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and tests
        run: mvn -B clean verify

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v2
        with:
          config: "p/ci" # regras públicas de CI; pode apontar para seu ruleset
          output: semgrep-results.sarif
        # semgrep-action já anota PRs e falha se achar problemas por padrão

      - name: Upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.sarif
