name: CI - build, test, SAST

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Permissão necessária para o upload de SARIF
      contents: read # Permissão para acessar o repositório

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and tests
        run: mvn -B clean verify

      - name: Run Semgrep (SAST)
        uses: semgrep/semgrep-action@v1 # Ação correta do Semgrep
        with:
          config: p/ci
          generateSarif: true
          sarif_file: semgrep.sarif # Gera o arquivo SARIF para análise

      - name: List files in the directory
        run: ls -alh # Verificando se o arquivo semgrep.sarif está presente

      - name: Upload Semgrep report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: ./semgrep.sarif # Certifique-se de que o caminho esteja correto

      - name: Upload SARIF to GitHub (Code Scanning)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./semgrep.sarif # Caminho correto para o arquivo SARIF
