name: SCA - dependency scan

on:
  schedule:
    - cron: "0 3 * * *" # nightly
  workflow_dispatch: {}
  pull_request:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: jeremylong/owasp-dependency-check-action@v4
        with:
          format: "ALL"
          failOnCVSS: "9"
          scan: "."

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report.html

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./dependency-check-report.sarif
